### ISSUE TITLE
Keyword matching erroneously considers prefixes of words

### ISSUE THREAD

**Issue by quephird** [quephird/MyOwnSQL#39]
Currently for statements like the following:

```
create table insert_table(some_column int);
```

... the lexer matches with the `insert` prefix of the table identifier. This is obviously not optimal, and users should be able to use names whose prefixes happen to coincide with built in keywords. Instead, the lexer should only match a string of characters which is _delimited_ by whitespace or other characters that denote punctuation in SQL (e.g., "(" or ",").

**Comment by Raj4478** [comment]
SELECT COMPANY.COMPANY_CODE,COMPANY.FOUNDER,COUNT(DISTINCT (LEAD_MANAGER_CODE)),COUNT(DISTINCT (SENIOR_MANAGER_CODE)),COUNT(DISTINCT(MANAGER_CODE)),COUNT(DISTINCT(EMPLOYEE_CODE))
FROM COMPANY
JOIN LEAD_MANAGER ON COMPANY.COMPANY_CODE = LEAD_MANAGER.COMPANY_CODE,
JOIN SENIOR_MANAGER ON COMPANY.COMPANY_CODE = SENIOR_MANAGER.COMPANY_CODE,
JOIN MANAGER ON COMPANY.COMPANY_CODE = MANAGER.COMPANY_CODE,
JOIN EMPLOYEE ON COMPANY.COMPANY_CODE = EMPLOYEE.EMPLOYEE_CODE
GROUP BY COMPANY.COMPANY_CODE,COMPANY.FOUNDER


Do you find any problem in this code ?

**Comment by quephird** [comment]
Addressed by https://github.com/quephird/MyOwnSQL/pull/40
